/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnDeath
void Wait(location lLoc)
{
CreateObject(OBJECT_TYPE_CREATURE, "carrionscavenger", lLoc);
}
void main()
{

object oPC = GetLastKiller();

if (!GetIsPC(oPC)) return;

object oTarget;
object oSpawn;
location lTarget;

lTarget = GetLocation(OBJECT_SELF);

DelayCommand(240.0, Wait(lTarget));

}

