location lTarget;
object oSpawn;
object oTarget;
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnEnter
#include "nw_i0_tool"
#include "nw_i0_generic"
void main()
{

   // DESTROYED WITH FIRE -AEZ
}
