/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnEnter
void main()
{
object oTarget;
oTarget = OBJECT_SELF;

DelayCommand(30.0, DestroyObject(oTarget, 0.0));

}

